# 数据源配置
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/base1?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: fangp
      password: "000000"
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      filters: stat, wall
      # 监控配置
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
        login-username: sysadmin
        login-password: "000000"
  freemarker:
        request-context-attribute: request
security:
  ignoring: "/static/**/*, /druid/**/**, /login.ftl, /webjars/**/*, /images/**/*"
  intercept: "/**/*.jsp, /**/*.html, /**/*.ftl"
  successUrl: "/index.ftl"
  logoutSuccessUrl: "/login.ftl"
# mybatis 配置
mybatis:
  type-aliases-package: com.github.peng.spring.boot.security.demo.mapper.model
  mapper-locations: classpath:mybatis/mapper/*.xml
# mapper 配置
mapper:
  identity: select uuid()
  before: true
logging:
  file: logs/security-demo.log